### ISSUE TITLE
Scaling DOM objects does not work in FireFox

### ISSUE THREAD

**Issue by IQAndreas** [senocular/TransformTool#1]
Using the latest commit, a0f1fb9ca9, the "DOM Scaling" examples do not work at all in FireFox ([video](http://www.youtube.com/watch?v=s7pVq4fS0qo)).

The "Canvas" version works just fine in FireFox, and both examples work flawlessly in Chrome.

Running:
- _32-bit Ubuntu 13.04_
- _FireFox 22.0_ (I can't find a more detailed "version" number like Chrome usually displays. Perhaps that's just how compact FireFox version numbers are.)

Oddly enough, I'm not getting any errors in JavaScript errors or warnings show up in the FireBug Console. I'm too inexperienced in this filthily untyped language to fix the issue on my own, but let me know if there is any way I can assist the debugging process.

**Comment by senocular** [comment]
You will need to update 

``` javascript
Picture.prototype.draw = function(){
    this.image.style.webkitTransform = this.transform.matrix.toString();
};
```

In the example code to use a non-webkit-specific transform (there may be other webkit-specific calls being made too, but that's one I know of offhand).

**Comment by senocular** [comment]
Also, I'm fairly certain the mouse position code is not cross-browser compatible (in fact might be webkit-specific as well)

**Comment by senocular** [comment]
I think webkit also has a different transformation origin than the other browsers, so that could require some additional finagling. I'll try to check in an update soon.
