### ISSUE TITLE
Independent Pivot

### ISSUE THREAD

**Issue by dhemmlerf** [senocular/TransformTool#8]
Hello.

The rotation pivot from the custom tool is not element independent, I mean if you change its position in one element, this is reflected in the other elements under de dom container. That behavior is present here:

http://senocular.github.io/TransformTool/examples/TransformDOMPictures.html

Is this a default feature or just a bug? Thanks.

**Comment by senocular** [comment]
I would say it's neither.  For the position to change for individual elements, there would be some sort of persistence needed to maintain the state of the pivot for each element.  The tool does not make any attempt to try and modify the element (potentially your elements) in some way that might be unexpected so it just keeps one pivot location stored and uses that for all elements.

With ES6, a weak map would be suitable for storing element locations without directly affecting the element itself in any noticeable way and could be used to implement this kind of persistence.  This code was written before those features were available, though.
